//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademico
{
    using System;

    public partial class Login
    {
        public int ID { get; set; }
        public string Enrollment { get; set; }
        public string Password { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
    
        public virtual AccountType AccountType { get; set; }
    }
}
