//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public int QualificationID { get; set; }
        public Nullable<int> Test { get; set; }
        public Nullable<int> Test2 { get; set; }
        public Nullable<int> Test3 { get; set; }
        public Nullable<int> Practice { get; set; }
        public Nullable<int> Attendance { get; set; }
        public Nullable<int> Record { get; set; }
        public Nullable<int> PensumID { get; set; }
    
        public virtual Pensum Pensum { get; set; }
    }
}
