//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seccion()
        {
            this.StudentSeccions = new HashSet<StudentSeccion>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> SebjectID { get; set; }
        public Nullable<int> TeacherID { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual Subject Subject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentSeccion> StudentSeccions { get; set; }
    }
}
