//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademico
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRecord
    {
        public int ID { get; set; }
        public string Student { get; set; }
        public string Materia { get; set; }
        public Nullable<int> P1 { get; set; }
        public Nullable<int> P2 { get; set; }
        public Nullable<int> P3 { get; set; }
        public Nullable<int> Asistencia { get; set; }
        public Nullable<int> Practica { get; set; }
        public Nullable<int> Nota { get; set; }
    }
}
