//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string Enrollment { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string IdentityCardNum { get; set; }
        public int GenderID { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
