//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademico
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSeccion
    {
        public int ID { get; set; }
        public Nullable<int> SeccionID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public byte[] FirstTest { get; set; }
        public string SecondTest { get; set; }
        public string ThirdTest { get; set; }
        public string Attendance { get; set; }
        public string Practice { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Seccion Seccion { get; set; }
    }
}
