//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        public int id_login { get; set; }
        public string usuario { get; set; }
        public string contraseña { get; set; }
        public string matricula { get; set; }
    }
}
