//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_loginprof
    {
        public int id_prof { get; set; }
        public string usuario_prof { get; set; }
        public string contraseña_prof { get; set; }
    }
}
