//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_matseleccion
    {
        public int id_matseleccion { get; set; }
        public string matricula { get; set; }
        public string materia { get; set; }
        public Nullable<int> nota1 { get; set; }
        public Nullable<int> nota2 { get; set; }
        public Nullable<int> nota3 { get; set; }
        public Nullable<int> practica { get; set; }
        public Nullable<int> asistencia { get; set; }
        public Nullable<int> notafinal { get; set; }
    }
}
