//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pensum
    {
        public int id_pensum { get; set; }
        public string clave { get; set; }
        public string asignatura { get; set; }
        public string prerequisito { get; set; }
        public Nullable<int> credito { get; set; }
    }
}
